// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDErJRv-PTrExiPOFUF95gqCgIXzZhVPNY',
    appId: '1:1078316392290:web:e2a88a821450cbcd8c563b',
    messagingSenderId: '1078316392290',
    projectId: 'eapp-d707b',
    authDomain: 'eapp-d707b.firebaseapp.com',
    storageBucket: 'eapp-d707b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3uRKb6EAQ6NDr8xiRZnXZGpTnzwkd-k',
    appId: '1:1078316392290:android:7ad552fece13d7808c563b',
    messagingSenderId: '1078316392290',
    projectId: 'eapp-d707b',
    storageBucket: 'eapp-d707b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9lypP5f6nHRbfqe9zgAY1QZ08flTfpFk',
    appId: '1:1078316392290:ios:8972c0df5849ac608c563b',
    messagingSenderId: '1078316392290',
    projectId: 'eapp-d707b',
    storageBucket: 'eapp-d707b.firebasestorage.app',
    iosBundleId: 'com.example.eApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9lypP5f6nHRbfqe9zgAY1QZ08flTfpFk',
    appId: '1:1078316392290:ios:8972c0df5849ac608c563b',
    messagingSenderId: '1078316392290',
    projectId: 'eapp-d707b',
    storageBucket: 'eapp-d707b.firebasestorage.app',
    iosBundleId: 'com.example.eApp',
  );
}
